# Pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\administrator\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

In [5]:
revenue = pd.Series([4200, 3800, 5100, 4700, 4100])
print(revenue)

0    4200
1    3800
2    5100
3    4700
4    4100
dtype: int64

In [6]:
revenue = pd.Series(
    [4200, 3800, 5100, 4700, 4100],
    index=["Jan", "Feb", "Mar", "Apr", "May"]
)
print(revenue)
print(revenue["Mar"])
print(revenue[revenue > 4000])

Jan    4200
Feb    3800
Mar    5100
Apr    4700
May    4100
dtype: int64
5100
Jan    4200
Mar    5100
Apr    4700
May    4100
dtype: int64

In [34]:
data = {
    "name":       ["Alice", "Bob", "Carol", "David", "Eve"],
    "department": ["Engineering", "Finance", "Engineering", "HR", "Finance"],
    "salary":     [85000, 72000, 91000, 65000, 78000],
    "active":     [True, True, False, True, True]
}

df = pd.DataFrame(data)
# print(df)
df

    name   department  salary  active
0  Alice  Engineering   85000    True
1    Bob      Finance   72000    True
2  Carol  Engineering   91000   False
3  David           HR   65000    True
4    Eve      Finance   78000    True

In [8]:
# print(df.shape)          # (rows, columns)
# print(df.dtypes)         # data type of each column
# print(df.columns)        # column names
# df.head(5)                # first 5 rows
# df.tail()               # last 3 rows
# df.info()                # column names, non-null counts, dtypes
# df.describe()            # statistics for numeric columns

In [9]:
# print(df.shape)
# print(df.dtypes)
print(df["department"].value_counts())

department
Engineering    2
Finance        2
HR             1
Name: count, dtype: int64

In [10]:
# print(df["name"])                        # one column — returns a Series
print(df[["name", "salary"]])            # multiple columns — returns a DataFrame

    name  salary
0  Alice   85000
1    Bob   72000
2  Carol   91000
3  David   65000
4    Eve   78000

In [11]:
# .loc — by label
print(df.loc[1])             # row with index label 2
# print(df.loc[1:3, "salary"])    # rows 1 to 3, name column

name              Bob
department    Finance
salary          72000
active           True
Name: 1, dtype: object

In [32]:
df

  full_name  annual_salary     city    band
0     Alice          85000  Karachi     Mid
1       Bob          80333      NaN     Mid
2     Carol          91000   Lahore  Senior
3     David          65000      NaN  Junior

In [13]:
# .iloc — by position
# print(df.iloc[0])
print(df.iloc[0:2, 0:2])

    name   department
0  Alice  Engineering
1    Bob      Finance

In [14]:
# Active employees only
# active = df[df["active"] == True]
# print(active)
# engineers = df[df["department"] == "Engineering"]
# print(engineers)


# Engineering department with salary above 80,000
senior_eng = df[(df["department"] == "Engineering") & (df["salary"] > 80000) & (df["active"] == True)]
print(senior_eng)

    name   department  salary  active
0  Alice  Engineering   85000    True

In [15]:
data = {
    "name":   ["Alice", "Bob", "Carol", "David"],
    "salary": [85000, None, 91000, 65000],
    "city":   ["Karachi", None, "Lahore", None]
}
df = pd.DataFrame(data)
df

    name   salary     city
0  Alice  85000.0  Karachi
1    Bob      NaN      NaN
2  Carol  91000.0   Lahore
3  David  65000.0      NaN

In [16]:
# print(df.isnull())          # True where value is missing
print(df.isnull().sum())    # count of missing per column

name      0
salary    1
city      2
dtype: int64

In [17]:
# Fill salary with mean, drop rows missing city
df["salary"] = df["salary"].fillna(df["salary"].mean())
df_clean = df.dropna(subset=["city"])
print(df_clean)

    name   salary     city
0  Alice  85000.0  Karachi
2  Carol  91000.0   Lahore

In [18]:
df

    name        salary     city
0  Alice  85000.000000  Karachi
1    Bob  80333.333333      NaN
2  Carol  91000.000000   Lahore
3  David  65000.000000      NaN

In [21]:
df = df.rename(columns={
    "name":   "full_name",
    "salary": "annual_salary"
})
print(df.columns)

Index(['full_name', 'annual_salary', 'city'], dtype='str')

In [22]:
df["annual_salary"] = df["annual_salary"].astype(int)
print(df.dtypes)

full_name          str
annual_salary    int64
city               str
dtype: object

In [26]:
def salary_band(annual_salary):
    if annual_salary >= 90000:
        return "Senior"
    elif annual_salary >= 75000:
        return "Mid"
    else:
        return "Junior"

df["band"] = df["annual_salary"].apply(salary_band)
print(df[["full_name", "annual_salary", "band"]])

  full_name  annual_salary    band
0     Alice          85000     Mid
1       Bob          80333     Mid
2     Carol          91000  Senior
3     David          65000  Junior

In [27]:
df

  full_name  annual_salary     city    band
0     Alice          85000  Karachi     Mid
1       Bob          80333      NaN     Mid
2     Carol          91000   Lahore  Senior
3     David          65000      NaN  Junior

In [30]:
# Sort by salary descending
print(df.sort_values("annual_salary", ascending=True)[["full_name", "annual_salary"]])

  full_name  annual_salary
3     David          65000
1       Bob          80333
0     Alice          85000
2     Carol          91000

In [35]:
summary = df.groupby("department")["salary"].mean()
print(summary)

department
Engineering    88000.0
Finance        75000.0
HR             65000.0
Name: salary, dtype: float64

In [36]:
summary = df.groupby("department")["salary"].agg(
    count="count",
    mean="mean",
    max="max"
)
print(summary)

             count     mean    max
department
Engineering      2  88000.0  91000
Finance          2  75000.0  78000
HR               1  65000.0  65000

In [37]:
employees = pd.DataFrame({
    "id":         [1, 2, 3, 4],
    "name":       ["Alice", "Bob", "Carol", "David"],
    "dept_id":    [10, 20, 10, 30]
})

departments = pd.DataFrame({
    "dept_id":   [10, 20, 40],
    "dept_name": ["Engineering", "Finance", "Marketing"]
})

In [42]:
# Inner join — only matched rows
# inner = pd.merge(employees, departments, on="dept_id", how="inner")
# print(inner)


# # Left join — all employees, NaN if no department match
left = pd.merge(employees, departments, on="dept_id", how="left")
print(left)

   id   name  dept_id    dept_name
0   1  Alice       10  Engineering
1   2    Bob       20      Finance
2   3  Carol       10  Engineering
3   4  David       30          NaN

In [45]:
df.to_csv("output.csv", index=False)

In [46]:
df.to_json("output.json", orient="records", indent=4)